
version: "3.8"

services:

  #  MySQL service
  mysql-db:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quarkus-microservices-orders-rest

  #  Kafka
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_MESSAGE_MAX_BYTES=100000000

  orders-rest:
    depends_on:
      - mysql-db
      - kafka
    build:
      context: ./orders-rest
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://mysql-db:3306/quarkus-microservices-orders-rest

  orders-notifier:
    depends_on:
      - kafka
    build:
      context: ./orders-notifier
    ports:
      - "8081:8081"
